next-version: 0.1.0
mode: Mainline
tag-prefix: '[vV]'
major-version-bump-message: '\+major'
minor-version-bump-message: '\+minor'
patch-version-bump-message: '\+patch'
commit-date-format: 'yyyy-MM-dd'
branches:
  master:
    tag: ''
    regex: ^master$
    increment: patch
    is-mainline: true
    is-release-branch: false
    track-merge-target: false
    tracks-release-branches: false
    prevent-increment-of-merged-branch-version: true

  feature:
    regex: ^feature/
    tag: useBranchName
    increment: Patch

  bug:
    regex: ^bug/
    tag: useBranchName
    increment: Patch
    source-branches:
      - master
