mode: Mainline
major-version-bump-message: '\+major'
minor-version-bump-message: '\+minor'
patch-version-bump-message: '\+patch'
commit-date-format: 'yyyy-MM-dd'
branches:
  master:
    regex: ^master$
    tag: ''
    increment: patch
    is-mainline: true

  feature:
    regex: ^(feature|features|feat)[/-]
    tag: useBranchName
    increment: Patch

  bug:
    regex: ^(bug|bugfix)[/-]
    tag: useBranchName
    increment: Patch
